var struct_zydis_decoded_instruction___1_1_zydis_decoded_instruction_avx___1_1_zydis_decoded_instruction_avx_conversion__ =
[
    [ "mode", "struct_zydis_decoded_instruction___1_1_zydis_decoded_instruction_avx___1_1_zydis_decoded_instruction_avx_conversion__.html#a0b4ff95404fc1c3c92eece16f4a6a2cd", null ]
];