var union___p_o_r_t_a_b_l_e___p_c_i___d_e_v_i_c_e___h_e_a_d_e_r =
[
    [ "_PORTABLE_PCI_EP_HEADER", "struct___p_o_r_t_a_b_l_e___p_c_i___d_e_v_i_c_e___h_e_a_d_e_r_1_1___p_o_r_t_a_b_l_e___p_c_i___e_p___h_e_a_d_e_r.html", "struct___p_o_r_t_a_b_l_e___p_c_i___d_e_v_i_c_e___h_e_a_d_e_r_1_1___p_o_r_t_a_b_l_e___p_c_i___e_p___h_e_a_d_e_r" ],
    [ "_PORTABLE_PCI_BRIDGE_HEADER", "struct___p_o_r_t_a_b_l_e___p_c_i___d_e_v_i_c_e___h_e_a_d_e_r_1_1___p_o_r_t_a_b_l_e___p_c_i___b_r_i_d_g_e___h_e_a_d_e_r.html", "struct___p_o_r_t_a_b_l_e___p_c_i___d_e_v_i_c_e___h_e_a_d_e_r_1_1___p_o_r_t_a_b_l_e___p_c_i___b_r_i_d_g_e___h_e_a_d_e_r" ],
    [ "ConfigSpaceEp", "union___p_o_r_t_a_b_l_e___p_c_i___d_e_v_i_c_e___h_e_a_d_e_r.html#a881c10de074ceb41023b13860619c3fe", null ],
    [ "ConfigSpacePtpBridge", "union___p_o_r_t_a_b_l_e___p_c_i___d_e_v_i_c_e___h_e_a_d_e_r.html#ae8d3b5634300aa352f28bf2e8a2f3f5c", null ]
];