var searchData=
[
  ['can_20clean_20project_3a_0',['finally you can clean project:',['../dir_10d681e7199b2631a1f96ba3e1aa3365.html#autotoc_md158',1,'']]],
  ['change_20an_20existing_20one_1',['Would you like to add a new feature or change an existing one?',['../md__c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md119',1,'']]],
  ['changed_2',['Changed',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md3',1,'Changed'],['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md6',1,'Changed'],['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md9',1,'Changed'],['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md12',1,'Changed'],['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md15',1,'Changed'],['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md18',1,'Changed'],['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md21',1,'Changed'],['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md24',1,'Changed'],['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md26',1,'Changed'],['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md29',1,'Changed'],['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md32',1,'Changed'],['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md35',1,'Changed'],['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md38',1,'Changed'],['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md41',1,'Changed'],['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md44',1,'Changed'],['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md47',1,'Changed'],['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md50',1,'Changed'],['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md53',1,'Changed'],['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md56',1,'Changed'],['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md59',1,'Changed'],['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md61',1,'Changed'],['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md64',1,'Changed'],['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md67',1,'Changed'],['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md70',1,'Changed'],['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md73',1,'Changed'],['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md75',1,'Changed'],['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md77',1,'Changed'],['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md80',1,'Changed'],['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md83',1,'Changed'],['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md86',1,'Changed'],['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md89',1,'Changed'],['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md92',1,'Changed'],['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md94',1,'Changed'],['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md96',1,'Changed'],['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md99',1,'Changed']]],
  ['changelog_3',['Changelog',['../md__c_h_a_n_g_e_l_o_g.html',1,'']]],
  ['clean_4',['Clean',['../dir_ed8ba861016ea0571a36ab05cf01358b.html#autotoc_md168',1,'']]],
  ['clean_20project_3a_5',['finally you can clean project:',['../dir_10d681e7199b2631a1f96ba3e1aa3365.html#autotoc_md158',1,'']]],
  ['code_6',['Do you have questions about the source code?',['../md__c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md120',1,'']]],
  ['code_20of_20conduct_7',['Code of Conduct',['../md__c_o_d_e___o_f___c_o_n_d_u_c_t.html',1,'Contributor Covenant Code of Conduct'],['../md_hwdbg_2_c_o_d_e___o_f___c_o_n_d_u_c_t.html',1,'Contributor Covenant Code of Conduct']]],
  ['code_20tree_8',['Source-code Tree',['../md__c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md121',1,'']]],
  ['coding_20style_9',['Coding Style',['../md__c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md115',1,'']]],
  ['conduct_10',['Conduct',['../md__c_o_d_e___o_f___c_o_n_d_u_c_t.html',1,'Contributor Covenant Code of Conduct'],['../md_hwdbg_2_c_o_d_e___o_f___c_o_n_d_u_c_t.html',1,'Contributor Covenant Code of Conduct']]],
  ['contribute_11',['How to contribute',['../dir_ad5958896612dc6ed06152ba9c3ee2ac.html#autotoc_md173',1,'']]],
  ['contributing_12',['Contributing',['../index.html#autotoc_md187',1,'']]],
  ['contributing_20to_20the_20linux_20port_13',['Contributing to the Linux Port',['../dir_ad5958896612dc6ed06152ba9c3ee2ac.html#autotoc_md171',1,'']]],
  ['contribution_14',['Contribution',['../md__c_o_n_t_r_i_b_u_t_i_n_g.html',1,'']]],
  ['contributor_20covenant_20code_20of_20conduct_15',['Contributor Covenant Code of Conduct',['../md__c_o_d_e___o_f___c_o_n_d_u_c_t.html',1,'Contributor Covenant Code of Conduct'],['../md_hwdbg_2_c_o_d_e___o_f___c_o_n_d_u_c_t.html',1,'Contributor Covenant Code of Conduct']]],
  ['contributors_16',['Contributors',['../md__c_r_e_d_i_t_s.html',1,'']]],
  ['covenant_20code_20of_20conduct_17',['Covenant Code of Conduct',['../md__c_o_d_e___o_f___c_o_n_d_u_c_t.html',1,'Contributor Covenant Code of Conduct'],['../md_hwdbg_2_c_o_d_e___o_f___c_o_n_d_u_c_t.html',1,'Contributor Covenant Code of Conduct']]],
  ['credits_3a_18',['Credits:',['../md__c_r_e_d_i_t_s.html#autotoc_md123',1,'']]]
];
